# Generated by Django 6.0.5 on 2026-06-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='given_name',
            new_name='first_name',
        ),
    ]
