# Generated by Django 6.0.5 on 2026-06-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_given_name_customer_first_name'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection(title)
            VALUES ('collection1')
        """, """
            DELETE FROM store_collection
            WHERE title='collection1'
        """)
    ]
